[tool.poetry]
name = "megamock"
version = "0.1.0"
description = "Mega mocking capabilities"
authors = ["James Hutchison <@JamesHutchison>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10 <4.0"
varname = {extras = ["asttokens"], version = "^0.10.0"}
asttokens = "^2.2.1"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
mypy = "^0.991"
flake8 = "^6.0.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
