[package]
name = "megamock"
version = "0.1.0-beta.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_megamock"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
defaultdict = "0.15.0"
once_cell = "1.17.1"
