name: Test
description: Install dependencies and run tests
runs:
  using: composite
  steps:
  - name: Install dependencies
    run: |
      python -m pip install --upgrade poetry
      poetry install --no-interaction
  - name: Lint with ruff
    run: |
      poetry run ruff $MEGAMOCK_FOLDERS
  - name: Lint with mypy
    run: |
      poetry run mypy .
  - name: Lint with pyright
    run: |
      poetry run pyright
  - name: Test with pytest
    run: |
      poetry run pytest